[package]
name = "futures-borrow"
version = "0.1.0"
authors = ["Carl Lerche <me@carllerche.com>"]

[dependencies]
futures = "0.1"

[replace]
"futures:0.1.16" = { git = "https://github.com/carllerche/futures-rs", branch = "test-harness" }
